name: Build
on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'build.sh'
      - 'Dockerfile'
      - 'erofs.patch'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          provenance: false
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/infrastructurex/erofs-utils:latest
            ghcr.io/infrastructurex/erofs-utils:1.8.9-patched
